Name: governanceMonitor.cronjob

Postgres:
  DataSource: host=127.0.0.1 user=postgres password=ZecreyProtocolDB@123 dbname=zecreylegend port=5432 sslmode=disable

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: myredis
    Type: node

ChainConfig:
  #  NetworkRPCSysConfigName: "BscTestNetworkRpc"
  NetworkRPCSysConfigName: "LocalTestNetworkRpc"
  GovernanceContractAddrSysConfigName: "GovernanceContract"
  #  StartL1BlockHeight: 520000
  StartL1BlockHeight: 0
  PendingBlocksCount: 0
  MaxHandledBlocksCount: 100000

