Name: proverClient.cronjob
Postgres:
  DataSource: host=172.22.41.88 user=postgres password=ZecreyProtocolDB@123 dbname=zecreylegend port=5432 sslmode=disable

CacheRedis:
  - Host: 172.22.41.88:6379
    # Pass: myredis
    Type: node

ProverHubRPC:
  Endpoints:
    - 127.0.0.1:8099

KeyPath:
  ProvingKeyPath: /root/zecreylegend/zecrey-legend/zecrey-legend.pk
  VerifyingKeyPath: /root/zecreylegend/zecrey-legend/zecrey-legend.vk
