Name: proverClient.cronjob
Postgres:
  DataSource: host=127.0.0.1 user=postgres password=ZecreyProtocolDB@123 dbname=zecreylegend port=5432 sslmode=disable

CacheRedis:
  - Host: 127.0.0.1:6379
    # Pass: myredis
    Type: node

ProverHubRPC:
  Endpoints:
    - 127.0.0.1:8099

KeyPath:
  ProvingKeyPath: /root/zkbas-deploy/zkbas/zkbas.pk
  VerifyingKeyPath: /root/zkbas-deploy/zkbas/zkbas.vk
