apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkbas.fullname" . }}
  labels:
    {{- include "zkbas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    zkbas.api: {{ include "zkbas.fullname" . }}-apiserver
    {{- include "zkbas.selectorLabels" . | nindent 4 }}
