name: Deploy zkbas on qa1

on:
  push:
    branches:
      - qa1

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Deploy new zkbas on qa1
        run: |
          echo 'fetch zkbas repo'
          export BRANCH=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

          cd ~
          rm -rf ./zkbas
          git clone --branch qa1 https://github.com/bnb-chain/zkbas.git
          cd ./zkbas

          sudo scp -r ./deploy-qa.sh "qa1:/tmp/"
          sudo ssh qa1 "sudo bash -x /tmp/deploy-qa.sh qa1;exit"
          echo "end deploy on qa1"

      - name: Notification via slack
        run: |
          export SLACK_WEBHOOK_URL=`sudo cat /home/ec2-user/actions-runner/slack-config.json | jq -r '.slack'`
          export JOB_STATUS=${{ job.status }}
          sudo scp -r qa1:/root/zkbas-deploy/zkbas-contract/info/addresses.json ~/addresses.json
          export ZkBas=`sudo cat ~/addresses.json  | jq -r '.zkbasProxy'`
          export AssetGov=`sudo cat ~/addresses.json  | jq -r '.assetGovernance'`
          curl -X POST $SLACK_WEBHOOK_URL --header 'Content-Type: application/json' \
          --data-raw '{ "author": "@'$GITHUB_ACTOR'", "status": "'$JOB_STATUS'", "ref": "'$GITHUB_REF'", "event": "'$GITHUB_EVENT_NAME'", "url": "'$GITHUB_SERVER_URL'/'$GITHUB_REPOSITORY'/commit/'$GITHUB_SHA'/checks", "ZkbasContract": "'$ZkBas'", "AssetGovContract": "'$AssetGov'" }'
          
