name: Deploy zkbnb on qa2

on:
  push:
    branches:
      - qa2

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Deploy new zkbnb on qa2
        run: |
          sudo ssh qa2 "cd /tmp && git clone --branch qa2 https://github.com/bnb-chain/zkbnb.git ;exit"
          sudo ssh qa2 "cd /tmp/zkbnb && sudo bash -x ./deploy-local.sh new kvrocks;exit"
          echo "end deploy on qa2"

      - name: Notification via slack
        run: |
          export SLACK_WEBHOOK_URL=`sudo cat /home/ec2-user/actions-runner/slack-config.json | jq -r '.slack'`
          export JOB_STATUS=${{ job.status }}
          sudo scp -r qa2:/root/zkbnb-deploy/zkbnb-contract/info/addresses.json ~/addresses.json
          export ZkBNB=`sudo cat ~/addresses.json  | jq -r '.zkbnbProxy'`
          export AssetGov=`sudo cat ~/addresses.json  | jq -r '.assetGovernance'`
          curl -X POST $SLACK_WEBHOOK_URL --header 'Content-Type: application/json' \
          --data-raw '{ "author": "@'$GITHUB_ACTOR'", "status": "'$JOB_STATUS'", "ref": "'$GITHUB_REF'", "event": "'$GITHUB_EVENT_NAME'", "url": "'$GITHUB_SERVER_URL'/'$GITHUB_REPOSITORY'/commit/'$GITHUB_SHA'/checks", "ZkBNBContract": "'$ZkBNB'", "AssetGovContract": "'$AssetGov'" }'
          
