name: zkBNB Integration Test

on:
  pull_request:
    branches:
      - qa
env:
  L1_ENDPOINT: https://data-seed-prebsc-2-s2.binance.org:8545
  L2_ENDPOINT: http://localhost:8888

jobs:
  deploy-zkBNB:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: deploy new zkbnb on runner
        if: ${{ !contains(github.event.pull_request.body, '/skip-integration-test') }}
        run: |
          echo ">>> Fetch zkbnb repo"
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo Pull requests $PR_NUMBER
          
          
          cd ~
          sudo rm -rf ./zkbnb
          git clone https://github.com/15000785133/zkbnb.git
          echo ">>> Integration tests run on commit id: $GITHUB_SHA"
          cd ./zkbnb
          git fetch origin pull/$PR_NUMBER/head:$GITHUB_SHA
          git checkout $GITHUB_SHA

          echo ">>> Start deploy new zkbnb"
          sudo bash ./deployment/tool/generate_api.sh
          go mod tidy
          docker image prune -f
          make docker-image
          sudo mkdir -p ./deployment/.zkbnb
          sudo cp ~/test.keyfile/* ./deployment/.zkbnb
          source <(sudo cat ~/.env)
          blockNr=$(sudo bash ./deployment/tool/tool.sh blockHeight)
          
          sudo BSC_TESTNET_RPC=${BSC_TESTNET_RPC} \
            BSC_TESTNET_PRIVATE_KEY=${BSC_TESTNET_PRIVATE_KEY} \
            COMMIT_BLOCK_PRIVATE_KEY=${COMMIT_BLOCK_PRIVATE_KEY} \
            VERIFY_BLOCK_PRIVATE_KEY=${VERIFY_BLOCK_PRIVATE_KEY} \
            VALIDATORS=${VALIDATORS} \
            SECURITY_COUNCIL_MEMBERS_NUMBER_1=${SECURITY_COUNCIL_MEMBERS_NUMBER_1} \
            SECURITY_COUNCIL_MEMBERS_NUMBER_2=${SECURITY_COUNCIL_MEMBERS_NUMBER_2} \
            SECURITY_COUNCIL_MEMBERS_NUMBER_3=${SECURITY_COUNCIL_MEMBERS_NUMBER_3} \
            bash ./deployment/tool/tool.sh all
          
          sudo bash ./deployment/docker-compose/docker-compose.sh down
          sudo COMMIT_BLOCK_PRIVATE_KEY=${COMMIT_BLOCK_PRIVATE_KEY} \
            VERIFY_BLOCK_PRIVATE_KEY=${VERIFY_BLOCK_PRIVATE_KEY} \
            bash ./deployment/docker-compose/docker-compose.sh up $blockNr
          echo ">>> Contract addresses"
          cat ~/zkbnb/deployment/dependency/zkbnb-contract/info/addresses.json
          echo ">>> Waiting 3m for the initialization tx to be verified"
          sleep 3m # Waiting for the initialization tx to be verified
          echo ">>> End deploy"

  integration-test:
    runs-on: self-hosted
    needs: deploy-zkBNB
    permissions:
      issues: write
      pull-requests: write
    steps:
     - name: run integration test
       if: ${{ !contains(github.event.pull_request.body, '/skip-integration-test') }}
       run: |
         source <(sudo cat ~/.env)
         export PATH=$PATH:/usr/local/go/bin:/usr/local/go/bin:/root/go/bin:/usr/local/bin
         
         cd /tmp && sudo rm -rf ./zkbnb-integration-test
         git clone --depth 1 --branch gkr-mimc https://${GH_PAT}@github.com/bnb-chain/zkbnb-integration-test.git
         cd ./zkbnb-integration-test && go mod tidy
         
         echo ">>>Start TestSetupSuite"
         ZkBNBGovernanceKey=${BSC_TESTNET_PRIVATE_KEY} \
           L1EndPoint=${L1_ENDPOINT} \
           L2EndPoint=${L2_ENDPOINT} \
           TestLogLevel=2 \
           go test -v -failfast -parallel 8 ./tests/integration/.../... --test.run '.*Suite' -testify.m "Test_01_batchToken"  -timeout 60m
