name: Issue Trigger

on:
  pull_request:
    types: [opened, edited, closed]
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  trigger:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: update-integration-keyfile
        if: contains(github.event.comment.body, '/update-integration-keyfile')   # check the comment if it contains the keywords
        run: |
          echo update-integration-keyfile